### ISSUE TITLE
Best practice ?when importing into a docker a set of files from another repository (wgbs_tools e.g.)

### ISSUE THREAD

**Issue by adeslatt** [adeslatt/methylSeqCaptureSeq#7]
What is the best practice when we need to containerize another repository?

Such as wgbs_tools

**Comment by meb326** [comment]
might be a little basic but:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Maybe this is helpful?
https://drupalize.me/tutorial/dockerize-existing-project?p=3040

**Comment by adeslatt** [comment]
Ok -- realized that this is completely a bad idea!   what one needs to do is containerize each of the dependencies and then use that docker in the workflow.   I forked the wgbs_tools and built a container - after we have tested I will ask Netaniel for a pull request.
